[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "libreoffice"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
